apiVersion: v1
kind: Pod
metadata:
  name: gnntracking-pod-aa
spec:
  containers:
  - name: mypod
    image: gitlab-registry.nrp-nautilus.io/aaportel/gnn-tracking:latest
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
