apiVersion: v1
kind: Pod
metadata:
  name: aa-pod
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/aaportel/gnn-tracking:latest
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    resources:
      limits:
        memory: 12Gi
        cpu: "2"
        nvidia.com/gpu: "1"
      requests:
        memory: 12Gi
        cpu: "1"
        nvidia.com/gpu: "1"

