apiVersion: v1
kind: Pod
metadata:
  name: aa-pod
spec:
  containers:
  - name: cpu-container
#    image: condaforge/mambaforge:latest
    image: gitlab-registry.nrp-nautilus.io/aaportel/gnn-tracking:latest
    command: ["sh", "-c", "echo 'Im a new pod' && sleep infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: "16"
      requests:
        memory: 32Gi
        cpu: "16"
    volumeMounts:
        - mountPath: /gnntrackingvol
          name: gnntrackingvol
  restartPolicy: Never
  volumes:
    - name: gnntrackingvol
      persistentVolumeClaim:
        claimName: gnntrackingvol


