apiVersion: v1
kind: Pod
metadata:
  name: aa-pod
spec:
  securityContext:
    fsGroup: 100
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/aaportel/mds-ml:latest
    command: ["/bin/bash", "-c"]
    args:
      - |
        sleep infinity
    resources:
      limits:
        memory: 32Gi
        cpu: "2"
        nvidia.com/gpu: "1"
      requests:
        memory: 32Gi
        cpu: "2"
        nvidia.com/gpu: "1"
  restartPolicy: Never
