apiVersion: v1
kind: Pod
metadata:
  name: aa-pod
spec:
  containers:
  - name: gpu-container
#    image: condaforge/mambaforge:latest
    image: gitlab-registry.nrp-nautilus.io/aaportel/gnn-tracking:latest
    command: ["/bin/bash", "-c", "echo 'Im a new pod' && sleep infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: "2"
        nvidia.com/gpu: "1"
      requests:
        memory: 32Gi
        cpu: "2"
        nvidia.com/gpu: "1"
    volumeMounts:
        - mountPath: /gnntrackingvol
          name: gnntrackingvol
  restartPolicy: Never
  volumes:
    - name: gnntrackingvol
      persistentVolumeClaim:
        claimName: gnntrackingvol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A40
            - NVIDIA-RTX-A6000
            - Quadro-RTX-8000


